name: Docker Build And Deploy

on:
  push:
    tags:
      - '*'
    branches:
      - "feature/ci-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get Latest Tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
    
    - name: Build Docker image
      run: |
        docker build . --tag valentinrudloff/pingbot:${{ steps.previoustag.outputs.tag }}

    - name: Docker Login
      env :
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $USERNAME -p $PASSWORD

    - name: Docker Push
      run: |
        docker push valentinrudloff/pingbot:${{ steps.previoustag.outputs.tag }}