name: Docker Build And Deploy

on:
  push:
    tags:
      - '*'
    branches:
      - "feature/ci-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILD_KIT: "1"
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        add_git_labels: true
        repository: valentinrudloff/pingbot
        push: true
        tags: pingbot_${{ env.RELEASE_VERSION }}
        labels: version="${{ env.RELEASE_VERSION }}"
