name: Docker Build And Deploy

on:
  push:
    tags:
      - '*'
    branches:
      - "feature/ci-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Retrieve Latest Tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Build Docker image
      run: |
        docker build . --tag ${{ env.RELEASE_VERSION }}

    - name: Docker Login
      env :
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $USERNAME -p $PASSWORD

    - name: Docker Push
      run: |
        docker push valentinrudloff/pingbot:1.0.0